import {Assistant} from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const assistant = Assistant({
  variable: "--font-sans",
  subsets: ["latin"],
});



export const metadata = {
  title: "אלדד קרמיסי -- ייעוץ משכנתאות",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="he" dir="rtl">
      <body className={assistant.variable}>
        <Header />
        {children}
      </body>
    </html>
  );
  }
